[book]
title = "Performance Profiling"
authors = ["Victor Dudochkin"]
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "src/theme"
default-theme = "navy"
site-url = "/performance-profiling/"